window.NTX_KEYWORDS = {
  alimentation: {
    pain: ["pain","baguette","miche","sandwich","toast","fougasse","pain de mie","pain complet","pain blanc","pain au lait"],
    viande: ["viande","bœuf","poulet","porc","poisson","chèvre","agneau","mouton","steak","côtelette","jambon","saucisse","charcuterie","brochette","grillade"],
    volaille: ["poulet","poule","coq","dinde","canard","pintade","volaille","poulet entier","poulet congelé","aile de poulet","cuisse de poulet"],
    poisson: ["poisson","tilapia","capitaine","sardine","maquereau","thon","poisson fumé","poisson salé","poisson frais","poisson séché"],
    riz: ["riz","riz blanc","riz brun","riz parfumé","riz brisé","riz complet","sac de riz","riz local","riz importé","riz basmati"],
    farine: ["farine","farine de blé","farine de maïs","farine de manioc","semoule","blé","maïs moulu","farine pâtisserie","farine complète","farine blanche"],
    manioc: ["manioc","fufu","chikwangue","cossette","tapioca","farine de manioc","feuilles de manioc","pondu","saka-saka","mpondu"],
    maïs: ["maïs","maïs en grains","maïs moulu","farine de maïs","épi de maïs","maïs frais","maïs sec","pop-corn","semoule de maïs","maïs doux"],
    huile: ["huile","huile de palme","huile de tournesol","huile d'arachide","huile de soja","huile végétale","huile raffinée","huile de coco","huile d'olive","huile alimentaire"],
    sucre: ["sucre","sucre blanc","sucre roux","sucre en poudre","sucre en morceaux","sucre glace","cassonade","sac de sucre","sucre brun","sucre vanillé"],
    sel: ["sel","sel de cuisine","sel iodé","gros sel","sel marin","sel fin","sel de table","sel gemme","sel rose","sel de mer"],
    lait: ["lait","lait frais","lait en poudre","lait concentré","lait écrémé","lait entier","lait caillé","lait de coco","lait de soja","lait chocolaté"],
    oeuf: ["œuf","œufs","œuf de poule","plateau d'œufs","œufs frais","œufs de caille","blanc d'œuf","jaune d'œuf","œuf dur","œuf frais"],
    légume: ["légume","légumes","légumes frais","légumes verts","légume local","légume du marché","tomate","oignon","chou","carotte","poireau","aubergine","concombre","poivron","haricot vert"],
    fruit: ["fruit","fruits","fruit frais","fruit local","banane","mangue","orange","avocat","papaye","ananas","pastèque","goyave","mandarine","citron","raisin"],
    tomate: ["tomate","tomates","tomate fraîche","tomate mûre","concentré de tomate","purée de tomate","tomate en boîte","tomate cerise","tomate locale","tomate rouge"],
    oignon: ["oignon","oignons","oignon rouge","oignon blanc","oignon vert","oignon doux","oignon frais","échalote","oignon séché","oignon en poudre"],
    pomme_de_terre: ["pomme de terre","patate","pommes de terre","patate douce","patate blanche","patate rouge","tubercule","frite","chips","purée de pomme de terre"],
    banane: ["banane","banane douce","banane plantain","plantain","banane à cuire","banane mûre","banane verte","banane séchée","banane de table","banane locale"],
    arachide: ["arachide","cacahuète","cacahuètes","pâte d'arachide","beurre d'arachide","arachide grillée","arachide crue","huile d'arachide","arachide salée","noix d'arachide"],
    épice: ["épice","épices","poivre","curry","paprika","gingembre","ail","piment","muscade","cannelle","clou de girofle","laurier","cumin","coriandre","persil"],
    boisson: ["boisson","boissons","eau","eau minérale","eau potable","bouteille d'eau","jus","jus de fruit","soda","coca","fanta","sprite","bière","vin","limonade"],
    café: ["café","café moulu","café soluble","grains de café","café en poudre","café noir","café au lait","café expresso","café filtre","café instantané"],
    thé: ["thé","thé vert","thé noir","thé en sachet","infusion","tisane","thé à la menthe","thé glacé","thé sucré","thé nature"],
    biscuit: ["biscuit","biscuits","gâteau","cookies","gauffrette","craquelin","sablés","petit beurre","gâteau sec","biscuit fourré"],
    conserve: ["conserve","boîte de conserve","sardine en boîte","thon en boîte","haricot en boîte","maïs en boîte","petit pois en boîte","conserve de viande","conserve de poisson","sauce en boîte"],
    fromage: ["fromage","fromage frais","fromage blanc","gruyère","cheddar","mozzarella","fromage râpé","fromage à tartiner","fromage de chèvre","fromage fondu"],
    beurre: ["beurre","beurre doux","beurre salé","margarine","beurre végétal","beurre de cuisine","beurre fondu","beurre clarifié","beurre allégé","beurre fermier"],
    yaourt: ["yaourt","yogourt","yaourt nature","yaourt aux fruits","yaourt sucré","yaourt brassé","yaourt à boire","yaourt grec","yaourt allégé","yaourt vanille"],
    pâtes: ["pâtes","spaghetti","macaronis","nouilles","tagliatelles","vermicelles","penne","lasagnes","raviolis","pâtes fraîches"],
    farine_patisserie: ["levure","levure boulangère","levure chimique","bicarbonate","gélatine","arôme vanille","chocolat en poudre","cacao en poudre","colorant alimentaire","vanille en poudre"],
    miel: ["miel","miel naturel","miel de forêt","pot de miel","miel d'acacia","miel de fleurs","miel liquide","miel crémeux","miel bio","miel pur"],
    confiture: ["confiture","gelée","marmelade","confiture de fraise","confiture d'abricot","confiture d'orange","confiture de mangue","confiture maison","confiture sucrée","confiture en pot"],
    sauce: ["sauce","sauce tomate","ketchup","mayonnaise","moutarde","sauce piquante","sauce barbecue","sauce soja","sauce vinaigrette","sauce blanche"],
    piment: ["piment","piment rouge","piment vert","piment fort","piment doux","piment séché","piment en poudre","piment frais","piment oiseau","poivre de cayenne"],
    citron: ["citron","citron vert","citron jaune","jus de citron","citron pressé","zeste de citron","citron confit","citron séché","citron frais","citron bio"],
    eau_minerale: ["eau minérale","eau de source","eau gazeuse","eau plate","eau en bouteille","eau en sachet","eau purifiée","eau distillée","eau de table","eau potable"],
    soda: ["soda","coca-cola","coca","fanta","sprite","pepsi","limonade","boisson gazeuse","boisson sucrée","boisson énergisante"],
    jus: ["jus","jus d'orange","jus de mangue","jus d'ananas","jus de pomme","jus naturel","nectar","jus concentré","jus en bouteille","jus frais"],
    viande_rouge: ["bœuf","viande de bœuf","steak","côte de bœuf","filet de bœuf","entrecôte","rôti de bœuf","viande hachée","bifteck","tournedos"],
    porc: ["porc","viande de porc","côtelette de porc","lard","jambon de porc","rôti de porc","saucisse de porc","bacon","travers de porc","filet de porc"],
    mouton: ["mouton","viande de mouton","agneau","gigot","côtelette d'agneau","épaule d'agneau","viande d'agneau","gigot d'agneau","ragoût d'agneau","mouton rôti"],
    escargot: ["escargot","escargots","escargot comestible","escargot frais","escargot préparé","escargot en boîte","escargot de mer","bigorneau","bulot","palourde"],
    crevette: ["crevette","crevettes","crevette fraîche","crevette séchée","crevette géante","gambas","crevette rose","crevette grise","crevette en boîte","crevette cuisinée"],
    crabe: ["crabe","crabes","crabe de mer","crabe frais","crabe en boîte","crabe cuisiné","pince de crabe","chair de crabe","crabe géant","crabe de rivière"],
    céréale: ["céréale","céréales","flocons d'avoine","muesli","corn flakes","son de blé","germe de blé","céréale petit déjeuner","avoine","avoine en flocons"],
    noix: ["noix","noix de cajou","amande","noisette","noix de coco","noix de pécan","noix du brésil","noix de macadamia","pistache","noix mélangées"],
    chips: ["chips","chips de pomme de terre","chips de banane","chips de manioc","chips croustillantes","chips salées","chips aromatisées","chips nature","chips au fromage","chips pimentées"],
    chocolat: ["chocolat","chocolat noir","chocolat au lait","chocolat blanc","tablette de chocolat","chocolat en poudre","bonbon au chocolat","truffes au chocolat","chocolat fourré","chocolat chaud"],
    bonbon: ["bonbon","bonbons","sucrerie","caramel","sucette","chewing-gum","réglisse","pastille","dragée","confiserie"],
    glace: ["glace","crème glacée","sorbet","esquimau","glace à l'eau","glace au lait","bâtonnet glacé","cornet de glace","glace en pot","glace familiale"],
    huile_aromatique: ["huile essentielle","huile parfumée","huile de massage","huile de ricin","huile de coco","huile de jojoba","huile d'amande","huile de sésame","huile de nigelle","huile de moutarde"],
    condiment: ["vinaigre","vinaigre blanc","vinaigre de cidre","vinaigre balsamique","sauce soja","nuoc-mâm","sauce poisson","bouillon cube","cube maggi","assaisonnement"]
  },

  logement: {
    maison: ["maison","appartement","villa","logement","résidence","studio","duplex","bungalow","habitation","pavillon"],
    parcelle: ["parcelle","terrain","concession","lot","terrain à bâtir","terrain agricole","terrain commercial","parcelle clôturée","lotissement","domaine"],
    chambre: ["chambre","chambre-salon","chambre simple","chambre meublée","chambre à louer","chambre d'étudiant","studio","chambre individuelle","chambre double","chambre familiale"],
    appartement: ["appartement","appartement à louer","appartement meublé","appartement neuf","appartement rénové","appartement spacieux","appartement sécurisé","appartement standing","appartement économique","appartement familial"],
    villa: ["villa","villa moderne","villa de luxe","villa avec piscine","villa avec jardin","villa sécurisée","villa standing","villa familiale","villa à louer","villa à vendre"],
    studio: ["studio","studio meublé","studio étudiant","studio à louer","petit studio","studio moderne","studio sécurisé","studio équipé","studio rénové","studio de standing"],
    propriete: ["propriété","propriété privée","propriété foncière","bien immobilier","immeuble","bâtiment","construction","édifice","domaine","domaine privé"],
    location: ["location","location maison","location appartement","location studio","location chambre","location villa","location terrain","location bureau","location local","location commerciale"],
    vente: ["vente","à vendre","vente maison","vente appartement","vente terrain","vente parcelle","vente villa","vente immeuble","vente propriété","vente commerciale"],
    quartier: ["quartier","commune","secteur","zone","arrondissement","localité","voisinage","milieu résidentiel","zone résidentielle","zone urbaine"],
    immeuble: ["immeuble","immeuble résidentiel","immeuble commercial","immeuble à vendre","immeuble à louer","immeuble de bureaux","immeuble d'habitation","bâtiment résidentiel","bâtiment moderne","gratte-ciel"],
    bureau: ["bureau","local professionnel","espace de travail","cabinet","open space","bureau individuel","bureau partagé","bureau meublé","bureau équipé","bureau à louer"],
    local: ["local","local commercial","espace commercial","boutique","magasin","point de vente","surface commerciale","local à louer","local à vendre","local professionnel"],
    entrepot: ["entrepôt","dépôt","espace de stockage","hangar","magasin de stockage","entrepôt à louer","entrepôt à vendre","entrepôt industriel","dépôt commercial","espace logistique"],
    parking: ["parking","garage","stationnement","place de parking","parking privé","parking public","parking sécurisé","box de parking","garage fermé","garage collectif"],
    meublé: ["meublé","appartement meublé","maison meublée","studio meublé","chambre meublée","local meublé","résidence meublée","location meublée","bureau meublé","villa meublée"],
    résidence: ["résidence","résidence privée","résidence sécurisée","résidence moderne","résidence haut standing","résidence universitaire","résidence familiale","résidence calme","résidence à louer","résidence à vendre"],
    construction: ["construction","maison en construction","chantier","gros œuvre","second œuvre","construction neuve","construction moderne","construction traditionnelle","maison à finir","chantier en cours"],
    rénovation: ["rénovation","maison à rénover","appartement à rénover","travaux","remise à neuf","réhabilitation","maison ancienne","bien à rénover","immeuble à rénover","local à rénover"],
    jardin: ["jardin","jardin privé","espace vert","cour","terrasse","balcon","véranda","patio","jardin potager","espace extérieur"],
    piscine: ["piscine","piscine privée","piscine commune","piscine sécurisée","piscine chauffée","piscine extérieure","bassin","pataugeoire","piscine de résidence","piscine de villa"],
    climatisation: ["climatisation","climatiseur","air conditionné","ventilation","chauffage","chauffe-eau","panneau solaire","groupe électrogène","installation électrique","installation sanitaire"],
    sécurité: ["sécurité","gardien","gardiennage","vidéosurveillance","alarme","portail sécurisé","clôture","interphone","accès contrôlé","résidence sécurisée"],
    terrain: ["terrain","terrain nu","terrain constructible","terrain clôturé","terrain titré","terrain avec titre","terrain à bâtir","terrain agricole","terrain industriel","terrain viabilisé"],
    titre: ["titre foncier","titre de propriété","acte de vente","certificat","papiers","documents","contrat","bail","titre de concession","permis de construire"],
    superficie: ["superficie","surface","mètre carré","m2","hectare","are","dimensions","étendue","mesure","taille du terrain"],
    quartier_residentiel: ["quartier résidentiel","zone résidentielle","quartier calme","quartier chic","quartier prisé","quartier populaire","quartier animé","quartier familial","quartier sécurisé","quartier proche centre"],
    centre_ville: ["centre-ville","plein centre","hyper centre","centre urbain","cœur de ville","centre commercial","zone piétonne","quartier d'affaires","zone administrative","zone économique"],
    périphérie: ["périphérie","banlieue","zone périurbaine","alentours","proche périphérie","quartier excentré","zone rurale","zone semi-urbaine","proche campagne","sortie de ville"],
    neuf: ["neuf","bien neuf","construction récente","immeuble neuf","appartement neuf","villa neuve","maison neuve","programme neuf","logement neuf","résidence neuve"],
    ancien: ["ancien","bien ancien","maison ancienne","appartement ancien","immeuble ancien","villa ancienne","logement ancien","construction ancienne","bâtiment ancien","bien de caractère"],
    standing: ["standing","haut standing","haut de gamme","luxe","prestige","standing élevé","standing moyen","standing économique","standing populaire","standing standard"],
    superficie_grande: ["grande superficie","spacieux","vaste","grand logement","grande maison","grand appartement","grande villa","grande parcelle","grand terrain","grande propriété"],
    petite_superficie: ["petite superficie","petit logement","petite maison","petit appartement","studio compact","mini studio","petite parcelle","petit terrain","logement compact","logement économique"],
    chambre_salon: ["chambre-salon","1 chambre salon","2 chambres salon","3 chambres salon","chambre salon cuisine","chambre salon douche","chambre-salon moderne","chambre-salon spacieux","chambre-salon neuf","chambre-salon économique"],
    cuisine: ["cuisine","cuisine équipée","cuisine moderne","cuisine américaine","cuisine séparée","cuisine ouverte","cuisine aménagée","coin cuisine","kitchenette","cuisine extérieure"],
    salle_de_bain: ["salle de bain","salle d'eau","douche","baignoire","sanitaire","toilette","wc","sanitaires modernes","salle de bain privée","salle de bain commune"],
    salon: ["salon","séjour","salon séjour","living","grand salon","salon spacieux","salon moderne","salon meublé","salle de séjour","salon familial"],
    chambre_coucher: ["chambre à coucher","chambre principale","chambre parentale","chambre d'amis","chambre d'enfant","chambre de maître","chambre spacieuse","chambre lumineuse","chambre calme","chambre climatisée"],
    balcon: ["balcon","terrasse","loggia","véranda","balcon privé","grande terrasse","terrasse couverte","terrasse aménagée","balcon vue dégagée","terrasse panoramique"],
    immeuble_bureaux: ["immeuble de bureaux","tour de bureaux","centre d'affaires","business center","bureaux modernes","espace de coworking","bureau partagé","plateau de bureaux","immeuble professionnel","centre professionnel"],
    hotel: ["hôtel","résidence hôtelière","auberge","guest house","maison d'hôtes","chambre d'hôte","appart-hôtel","motel","hébergement touristique","hébergement temporaire"],
    location_courte_duree: ["location courte durée","location journalière","location hebdomadaire","location vacances","location temporaire","location saisonnière","airbnb","location meublée courte durée","location étudiant","location passage"],
    colocation: ["colocation","chambre partagée","appartement partagé","location partagée","colocataire","partage de logement","chambre en colocation","chambre à partager","logement partagé","studio partagé"],
    maison_familiale: ["maison familiale","villa familiale","maison pour famille","grande maison familiale","logement familial","maison avec plusieurs chambres","maison pour grande famille","maison spacieuse","maison confortable","maison de famille"],
    maison_vacances: ["maison de vacances","villa de vacances","résidence secondaire","maison de campagne","maison de plage","résidence de vacances","logement touristique","maison week-end","villa de loisirs","maison de retraite"],
    investissement: ["investissement","placement immobilier","rendement locatif","achat investissement","bien locatif","immeuble de rapport","appartement locatif","villa locative","terrain d'investissement","placement foncier"]
  },

  vehicule: {
    voiture: ["voiture","auto","automobile","véhicule","taxi","camion","4x4","berline","citadine","suv","pick-up","utilitaire","familiale","monospace","coupé","cabriolet","limousine","jeep","van","minibus","bus","car","camionnette","fourgon","break","compacte","hybride","électrique","diesel","essence"],
    moto: ["moto","scooter","mobylette","motocyclette","cyclomoteur","moto-cross","roadster","sportive","trail","custom","tricycle","tuk-tuk","quad","deux-roues","moto-taxi"],
    velo: ["vélo","bicyclette","vtt","vélo de route","vélo électrique","vae","tricycle","vélo enfant","vélo de ville","vélo pliant","bicross","bmx","vélo de course","vélo tandem","vélo cargo"],
    pieces: ["pièces","pièces détachées","pièces auto","pièces moto","accessoires","moteur","boîte de vitesse","embrayage","frein","amortisseur","filtre","bougie","courroie","alternateur","démarreur","radiateur","pompe à eau","turbo","échappement","pot d'échappement"],
    pneu: ["pneu","pneus","pneumatique","pneu neuf","pneu occasion","pneu hiver","pneu été","pneu 4 saisons","roue","jante","chambre à air","pneu moto","pneu voiture","pneu camion","pneu tout-terrain"],
    batterie: ["batterie","batterie auto","batterie moto","batterie camion","batterie 12v","batterie 24v","batterie neuve","batterie occasion","batterie rechargeable","accumulateur"],
    moteur: ["moteur","moteur diesel","moteur essence","moteur neuf","moteur occasion","moteur reconditionné","moteur de voiture","moteur de moto","moteur de camion","groupe moteur"],
    carrosserie: ["carrosserie","carrosserie auto","tôle","portière","capot","coffre","pare-chocs","aile","toit","rétroviseur","pare-brise","vitre","phare","feu arrière","clignotant"],
    entretien: ["entretien","entretien auto","vidange","révision","contrôle technique","lavage","nettoyage","graissage","changement d'huile","filtre à huile","bougie","plaquette de frein","disque de frein","courroie de distribution","courroie accessoire"],
    mécanique: ["mécanicien","garage","atelier","réparation","dépannage","remorquage","diagnostic","révision moteur","réparation moteur","réparation boîte","réparation frein","réparation suspension","réparation électricité","réparation climatisation","réparation carrosserie"],
    location_vehicule: ["location voiture","location moto","location véhicule","location utilitaire","location camion","location bus","location avec chauffeur","location sans chauffeur","location longue durée","location courte durée","location leasing"],
    achat: ["achat","achat voiture","achat moto","achat véhicule","achat camion","achat utilitaire","achat neuf","achat occasion","achat leasing","achat comptant","achat crédit"],
    vente: ["vente","vente voiture","vente moto","vente véhicule","vente camion","vente utilitaire","vente neuve","vente occasion","vente comptant","vente crédit","vente leasing"],
    marque: ["toyota","nissan","honda","mitsubishi","suzuki","hyundai","kia","ford","chevrolet","volkswagen","mercedes","bmw","audi","peugeot","renault","citroën","fiat","dacia","isuzu","mazda","subaru","land rover","jeep","tesla","byd"],
    modele: ["corolla","camry","hilux","prado","rav4","land cruiser","civic","accord","crv","pajero","l200","outlander","swift","vitara","sportage","tucson","elantra","ranger","focus","golf"],
    puissance: ["puissance","chevaux","cv","ch","kilowatt","kw","couple","cylindrée","turbo","atmosphérique","injection","carburateur","boîte automatique","boîte manuelle","4x4","2x4","traction","propulsion"],
    kilometrage: ["kilométrage","km","kilomètres","compteur","faible kilométrage","haut kilométrage","km certifiés","km d'origine","km réel","km compteur"],
    carburant: ["essence","diesel","gasoil","gpl","électrique","hybride","rechargeable","hydrogène","bio-carburant","carburant fossile"],
    couleur: ["couleur","blanc","noir","gris","rouge","bleu","vert","jaune","orange","marron","beige","argent","doré","bordeaux","turquoise","violet","rose","crème"],
    état: ["état neuf","très bon état","bon état","état moyen","à réparer","pour pièces","roulant","non roulant","accidenté","reconditionné"],
    assurance: ["assurance","assurance auto","assurance moto","assurance tous risques","assurance au tiers","carte rose","attestation","police d'assurance","assurance temporaire","assurance annuelle"],
    documents: ["carte grise","carte rose","permis de conduire","certificat d'immatriculation","acte de vente","facture","certificat de conformité","contrôle technique","vignette","assurance"],
    transport: ["transport","transport de personnes","transport de marchandises","transport scolaire","transport urbain","transport interurbain","transport en commun","transport privé","transport de fonds","transport de conteneurs"],
    taxi: ["taxi","taxi collectif","taxi privé","taxi moto","taxi vélo","taxi bus","taxi urbain","taxi interurbain","taxi de nuit","taxi de jour"],
    moto_taxi: ["moto-taxi","taxi-moto","moto transport","moto de ville","moto urbaine","moto économique","moto de livraison","moto avec casque","moto pour deux","moto partagée"],
    utilitaire: ["utilitaire","fourgon","fourgonnette","camionnette","pick-up","van","minibus","ambulance","corbillard","food-truck","camion frigo","camion citerne","camion benne","camion plateau","dépanneuse"],
    engin: ["engin","engin de chantier","tractopelle","pelleteuse","bulldozer","grue","chariot élévateur","compacteur","niveleuse","chargeuse","mini-pelle","tracteur agricole","moissonneuse","engin forestier","engin portuaire"],
    remorque: ["remorque","remorque auto","remorque moto","remorque bagagère","remorque plateau","semi-remorque","porte-voiture","caravane","camping-car","remorque frigorifique"],
    tuning: ["tuning","personnalisation","customisation","jantes alu","kit carrosserie","échappement sport","filtre sport","suspension sport","led tuning","covering"],
    accessoires: ["accessoires auto","accessoires moto","autoradio","gps","caméra de recul","radar de recul","chargeur","support téléphone","coffre de toit","barres de toit","tapis","housse de siège","volant sport","siège bébé","kit mains libres"],
    électrique: ["véhicule électrique","voiture électrique","moto électrique","vélo électrique","scooter électrique","trottinette électrique","borne de recharge","wallbox","câble de recharge","autonomie électrique"],
    neuf_ou_occasion: ["véhicule neuf","véhicule d'occasion","deuxième main","première main","faible km","full options","toutes options","basique","entrée de gamme","haut de gamme"]
  },

  electronique: {
    telephone: ["téléphone","portable","smartphone","mobile","cellulaire","iphone","samsung","tecno","infinix","itel","huawei","xiaomi","oppo","vivo","nokia","google pixel","honor","realme","oneplus","sony"],
    ordinateur: ["ordinateur","pc","laptop","ordinateur portable","desktop","macbook","imac","chromebook","lenovo","hp","dell","asus","acer","msi","toshiba","samsung","surface","thinkpad","ideapad","pavilion"],
    tablette: ["tablette","ipad","tablette android","samsung tab","lenovo tab","huawei mediapad","surface pro","tablette tactile","tablette graphique","tablette électronique"],
    tv: ["tv","télévision","téléviseur","écran tv","smart tv","tv led","tv oled","tv qled","tv 4k","tv 8k","tv samsung","tv lg","tv sony","tv tcl","tv hisense","tv philips","tv panasonic","tv sharp"],
    ecran: ["écran","moniteur","écran pc","écran ordinateur","écran gaming","écran incurvé","écran 4k","écran full hd","écran tactile","display","affichage"],
    audio: ["écouteurs","casque","casque audio","écouteurs bluetooth","airpods","casque bluetooth","casque filaire","écouteurs sans fil","earbuds","intra-auriculaires","casque gamer","casque studio","casque réduction de bruit","barre de son","haut-parleur","enceinte","enceinte bluetooth","baffle","chaîne hi-fi","home cinéma"],
    accessoires: ["chargeur","câble usb","câble type c","lightning","adaptateur","convertisseur","hub usb","dock","station d'accueil","support téléphone","coque","protection écran","verre trempé","étui","housse","clavier","souris","tapis souris","webcam","microphone"],
    composants: ["processeur","cpu","carte graphique","gpu","carte mère","ram","mémoire","barrette mémoire","disque dur","ssd","disque externe","alimentation","boîtier","ventilateur","refroidissement","watercooling","pile","batterie","onduleur","multiprise"],
    imprimante: ["imprimante","scanner","photocopieuse","imprimante multifonction","imprimante laser","imprimante jet d'encre","imprimante photo","imprimante 3d","cartouche","toner","papier","ramette","encre"],
    reseau: ["routeur","modem","box internet","wifi","répéteur wifi","amplificateur wifi","point d'accès","switch réseau","câble réseau","ethernet","rj45","fibre optique","antenne wifi","antenne 4g","antenne satellite","décodeur","parabole","récepteur satellite"],
    photo: ["appareil photo","caméra","caméra numérique","appareil photo reflex","appareil photo compact","appareil photo hybride","gopro","action cam","drone","caméra de surveillance","cctv","webcam","objectif","trépied","flash","carte mémoire","carte sd","micro sd","clé usb"],
    objet_connecte: ["montre connectée","smartwatch","bracelet connecté","smartband","montre intelligente","airtag","traceur gps","gps","navigateur","assistant vocal","enceinte connectée","caméra connectée","ampoule connectée","prise connectée","domotique"],
    console: ["playstation","ps4","ps5","xbox","nintendo","switch","console de jeu","manette","joystick","jeu vidéo","casque vr","réalité virtuelle","gaming","gamer","pc gamer","chaise gaming","bureau gaming","souris gaming","clavier gaming"],
    logiciel: ["logiciel","application","app","programme","système d'exploitation","windows","macos","linux","android","ios","office","word","excel","powerpoint","antivirus","vpn","navigateur web","chrome","firefox","edge"],
    tv_box: ["tv box","android tv","chromecast","fire stick","apple tv","box tv","décodeur tv","décodeur canal","décodeur startimes","abonnement tv","canal+","startimes","netflix","prime video","disney+","youtube premium","spotify"],
    jeu_video: ["jeu","jeux vidéo","fifa","pes","call of duty","gta","minecraft","fortnite","pubg","free fire","roblox","jeu mobile","jeu pc","jeu console","jeu en ligne"],
    streaming: ["streaming","netflix","amazon prime","disney+","canal+","startimes","youtube","tiktok","instagram","facebook","whatsapp","télégram","signal","snapchat","twitter","linkedin"],
    crypto: ["crypto","bitcoin","ethereum","usdt","binance","wallet crypto","minage","blockchain","nft","token","crypto-monnaie","carte crypto","ledger","trezor"],
    composant_pc: ["processeur intel","amd ryzen","nvidia","geforce","radeon","core i3","core i5","core i7","core i9","ryzen 3","ryzen 5","ryzen 7","ryzen 9","ssd nvme","ddr4","ddr5","rtx 3060","rtx 4070","gtx 1650"],
    peripherique: ["imprimante 3d","scanner 3d","stylet","tablette graphique","écran tactile","écran interactif","vidéoprojecteur","projecteur","mini projecteur","tableau interactif","pointeur","présentateur"],
    baterie_charge: ["power bank","batterie externe","chargeur rapide","chargeur sans fil","chargeur multiple","chargeur solaire","chargeur voiture","câble renforcé","câble tressé","câble magnétique"],
    montres: ["montre","montre homme","montre femme","montre enfant","montre classique","montre sportive","montre luxe","montre connectée","bracelet","bijou connecté","fitbit","garmin"],
    casque_realite: ["casque vr","casque réalité virtuelle","lunettes vr","oculus","meta quest","playstation vr","htc vive","réalité augmentée","réalité mixte","immersive"],
    cryptomonnaie: ["crypto","bitcoin","ethereum","usdt","binance","wallet","minage","blockchain","nft","token","carte crypto","ledger","trezor","metamask","coinbase"],
    domotique: ["domotique","maison connectée","objet connecté","iot","ampoule connectée","prise connectée","caméra intérieure","capteur","alarme connectée","serrure connectée","thermostat connecté","assistant vocal","google home","alexa","echo"],
    drone: ["drone","drone caméra","drone professionnel","drone de course","drone de loisir","drone agricole","drone de livraison","drone de surveillance","drone militaire","drone jouet"],
    e_sport: ["e-sport","esport","tournoi gaming","compétition gaming","équipe gaming","joueur pro","streamer","youtubeur gaming","twitch","kick"],
    impression: ["imprimante thermique","imprimante mobile","imprimante portable","imprimante bluetooth","imprimante à étiquettes","imprimante ticket","imprimante code-barres","imprimante a4","imprimante a3","imprimante couleur"],
    scanner_caisse: ["caisse enregistreuse","scanner code-barres","lecteur code-barres","terminal point de vente","tpe","terminal de paiement","caisse tactile","caisse mobile","caisse ipad","logiciel caisse"],
    securite_elec: ["caméra ip","caméra wifi","caméra filaire","caméra extérieure","caméra intérieure","nvr","dvr","enregistreur vidéo","détecteur de mouvement","détecteur de fumée","alarme intrusion","alarme incendie","interphone vidéo","visiophone"]
  },

  services: {
    emploi: ["emploi","travail","job","poste","recrutement","carrière","vacance","opportunité","offre d'emploi","candidature","cv","lettre de motivation","entretien","stage","apprentissage","alternance","cdi","cdd","intérim","temps partiel","temps plein","freelance","mission","consultant","prestataire","indépendant","entrepreneur","auto-emploi","profession libérale","fonction publique","secteur privé","ong","association","administration","salarié","employé","ouvrier","technicien","agent","cadre","manager","directeur","chef d'équipe","superviseur","coordinateur","assistant","secrétaire","réceptionniste","comptable","caissier","vendeur","commercial","chauffeur","livreur","agent de sécurité","agent d'entretien","cuisinier","serveur","barman","femme de chambre","réceptionniste hôtel","guide touristique","animateur","professeur","enseignant","formateur","éducateur","infirmier","médecin","pharmacien","dentiste","sage-femme","kinésithérapeute","opticien","psychologue","assistant social","juriste","avocat","notaire","ingénieur","architecte","urbaniste","géomètre","topographe","informaticien","développeur","webmaster","designer","graphiste","community manager","journaliste","photographe","vidéaste","monteur","réalisateur","animateur 3d"],
    ecole: ["école","école primaire","école secondaire","école maternelle","lycée","collège","université","institut","faculté","campus","formation","éducation","enseignement","cours","leçon","examen","concours","diplôme","certificat","attestation","étudiant","élève","apprenant","inscription","rentrée scolaire","frais scolaires","internat","externat","pensionnat","cantine","garderie","crèche","centre de formation","formation professionnelle","formation continue","cours du soir","cours en ligne","e-learning","tutorat","soutien scolaire","alphabétisation"],
    sante: ["santé","médecin","docteur","clinique","hôpital","centre de santé","dispensaire","polyclinique","cabinet médical","pharmacie","pharmacien","médicament","ordonnance","consultation","urgence","ambulance","soins","infirmier","infirmière","sage-femme","gynécologue","pédiatre","dentiste","ophtalmologue","opticien","kinésithérapeute","psychologue","psychiatre","radiologue","laboratoire","analyse","radiographie","échographie","scanner","irm","vaccin","vaccination","analyse de sang","test covid","test paludisme","maternité","accouchement","grossesse","pédiatrie","cardiologie","dermatologie","chirurgie","opération","hospitalisation","assurance santé","mutuelle","carnet de santé"],
    transport: ["transport","transporteur","taxi","taxi-moto","bus","minibus","camion","camionnette","déménagement","déménageur","livraison","livreur","coursier","logistique","fret","fret aérien","fret maritime","transitaire","douane","dédouanement","colis","envoi","réception colis","entrepôt logistique","distribution","approvisionnement","transport international","transport national","transport urbain","transport interurbain"],
    immobilier: ["agent immobilier","agence immobilière","courtier","promoteur immobilier","gestion locative","syndic","gérance","vente immobilière","achat immobilier","location immobilière","estimation immobilière","expertise immobilière","conseil immobilier","investissement immobilier","gestion de patrimoine"],
    beaute: ["coiffure","coiffeur","coiffeuse","salon de coiffure","barbier","tresse","tresses","nattes","défrisage","coloration","mèches","perruque","extension","onglerie","manucure","pédicure","maquillage","maquilleuse","esthétique","soins du visage","soins du corps","massage","spa","hammam","institut de beauté","parfumerie","parfum","cosmétique","produit de beauté","maquillage professionnel"],
    informatique: ["informaticien","développeur","développeur web","développeur mobile","développeur logiciel","ingénieur informatique","technicien informatique","administrateur réseau","administrateur système","webmaster","webdesigner","graphiste","designer ui","designer ux","community manager","expert référencement","seo","référencement","rédacteur web","traducteur","data analyst","data scientist","cybersécurité","cloud computing","devops","testeur qa","chef de projet informatique","formateur informatique","maintenance informatique","dépannage informatique","installation réseau"],
    artisanat: ["artisan","artisanat","menuisier","ébéniste","charpentier","maçon","carreleur","plombier","électricien","peintre","soudeur","mécanicien","tôlier","cordonnier","tailleur","couturier","styliste","modéliste","bijoutier","orfèvre","potier","céramiste","sculpteur","peintre en bâtiment","carreleur","marbreur","vitrier","couvreur","forgeron","chaudronnier","serrurier"],
    restauration: ["restauration","restaurant","restaurateur","cuisinier","chef cuisinier","pâtissier","boulanger","boucher","charcutier","poissonnier","épicier","traiteur","service traiteur","service à domicile","livraison repas","fast-food","snack","cafétéria","buvette","bar","pub","salon de thé","pizzeria","crêperie","grilladerie","food-truck"],
    finance: ["finance","banque","microfinance","coopérative","mobile money","airtel money","orange money","m-pesa","m-pesa","western union","moneygram","transfert d'argent","change","bureau de change","crédit","micro-crédit","prêt","épargne","compte bancaire","carte bancaire","assurance","mutuelle","plan épargne"],
    juridique: ["juriste","avocat","notaire","huissier","conseil juridique","assistance juridique","contentieux","litige","procès","tribunal","cour d'appel","cour suprême","acte notarié","contrat","rédaction contrat","création société","enregistrement société","droit des affaires","droit du travail","droit foncier","propriété intellectuelle","marque déposée","brevet"],
    evenementiel: ["événementiel","organisateur événement","wedding planner","mariage","anniversaire","baptême","funérailles","décorateur","location chaises","location tables","location chapiteau","location tente","sonorisation","dj","animation","traiteur mariage","photographe mariage","vidéaste mariage","salle de fête","salle de réception","séminaire","conférence","formation événement"],
    nettoyage: ["nettoyage","société de nettoyage","femme de ménage","agent d'entretien","repassage","lessive","blanchisserie","pressing","lavage auto","lavage tapis","nettoyage bureaux","nettoyage fin de chantier","désinfection","dératisation","désinsectisation","jardinage","entretien espaces verts","élagage","tonte pelouse"],
    securite: ["sécurité","agent de sécurité","gardiennage","société de gardiennage","vidéosurveillance","installation alarme","télésurveillance","serrurier","coffre-fort","blindage","protection rapprochée","conseil sécurité","audit sécurité","cybersécurité","sécurité informatique"],
    publicite: ["publicité","agence de publicité","communication","marketing","marketing digital","community management","réseaux sociaux","création site web","référencement","google ads","facebook ads","impression flyers","impression bâches","impression t-shirts","sérigraphie","panneaux publicitaires","affichage","spots radio","sponsoring"],
    formation_pro: ["formation professionnelle","centre de formation","formateur","coach","coaching","mentorat","séminaire professionnel","atelier formation","certification","qualification","recyclage professionnel","formation continue","e-learning","mooc","tutorat professionnel"]
  },

  villes_quartiers: {
    kinshasa: ["kinshasa","kin","kin la belle","capitale","kinshasa gombe","kinshasa limete","kinshasa lingwala","kinshasa kalamu","kinshasa masina","kinshasa ngaliema","kinshasa bandalungwa","kinshasa kintambo","kinshasa lemba","kinshasa matete","kinshasa ndjili","kinshasa tshangu","kinshasa mont ngafula","kinshasa maluku","kinshasa nsele","kinshasa kasavubu","kinshasa kasa-vubu","kinshasa selembao","kinshasa ngaba","kinshasa makala","kinshasa kisenso","kinshasa kimbanseke","kinshasa n'djili","kinshasa matete"],
    gombe: ["gombe","la gombe","kin gombe","centre des affaires","quartier des affaires","bld du 30 juin","avenue du commerce","place royale"],
    limete: ["limete","limete industriel","limete résidentiel","limete 7ème rue","limete kingabwa","limete salongo"],
    lingwala: ["lingwala","lingwala kinshasa","quartier lingwala","av. kasavubu"],
    kalamu: ["kalamu","kalamu kinshasa","kalamu 1","kalamu 2","kalamu yaba","kalamu matonge","kalamu bandal"],
    bandalungwa: ["bandal","bandalungwa","bandal kinshasa","bandal kasa-vubu","bandal matonge"],
    kintambo: ["kintambo","kintambo magasin","kintambo kinshasa","kintambo joli parc"],
    ngaliema: ["ngaliema","ngaliema kinshasa","ma campagne","joli parc","mont fleury","binza","binza meteo","binza delvaux","binza ipi","binza pigeon","binza upn","macampagne"],
    masina: ["masina","masina kinshasa","masina sans fil","masina kimbangu","masina quartier 7","masina petro congo"],
    ndjili: ["ndjili","n'djili","ndjili kinshasa","ndjili aéroport","ndjili international"],
    lemba: ["lemba","lemba kinshasa","lemba super","lemba i","lemba ii","lemba village"],
    matete: ["matete","matete kinshasa","matete bonhomme","matete tomba","matete lieu saint"],
    makala: ["makala","makala kinshasa","makala sans fil","makala sous-r centralégion"],
    selembao: ["selembao","selembao kinshasa","selembao cité verte","selembao camp luka"],
    ngaba: ["ngaba","ngaba kinshasa","ngaba rond-point","ngaba bongolo"],
    kisenso: ["kisenso","kisenso kinshasa","kisenso 1","kisenso 2","kisenso 3"],
    kimbanseke: ["kimbanseke","kimbanseke kinshasa","kimbanseke mikonga","kimbanseke nsanga"],
    maluku: ["maluku","maluku kinshasa","maluku menkao","maluku nsele","maluku plaine"],
    nsele: ["nsele","n'sele","nsele kinshasa","nsele buma","nsele kinkole"],
    lubumbashi: ["lubumbashi","lubum","l'shi","lubumbashi katuba","lubumbashi kampemba","lubumbashi ruashi","lubumbashi annexe","lubumbashi kenia","lubumbashi kamalondo","lubumbashi dilala","lubumbashi gecamines","lubumbashi bel-air","lubumbashi gambela"],
    katuba: ["katuba","katuba lubumbashi","katuba 1","katuba 2","katuba 3"],
    kampemba: ["kampemba","kampemba lubumbashi","kampemba industriel"],
    ruashi: ["ruashi","ruashi lubumbashi","ruashi minier","ruashi minière"],
    annexe: ["annexe","annexe lubumbashi","annexe 1","annexe 2","annexe 3"],
    kenia: ["kenia","kenia lubumbashi","kenia marché"],
    kamalondo: ["kamalondo","kamalondo lubumbashi","kamalondo stade"],
    dilala: ["dilala","dilala lubumbashi","dilala résidentiel"],
    gambela: ["gambela","gambela lubumbashi","gambela centre"],
    bel_air: ["bel-air","bel air lubumbashi","bel-air résidentiel"],
    kasumbalesa: ["kasumbalesa","kasumbalesa frontière","kasumbalesa poste","kasumbalesa douane"],
    kolwezi: ["kolwezi","kolwezi lualaba","kolwezi minier","kolwezi dilala"],
    likasi: ["likasi","likasi katanga","likasi industriel"],
    kikwit: ["kikwit","kikwit kwilu","kikwit ville"],
    matadi: ["matadi","matadi port","matadi bas-congo","matadi kongo"],
    bukavu: ["bukavu","bukavu kivu","bukavu sud-kivu","bukavu kadutu","bukavu ibanda"],
    goma: ["goma","goma nord-kivu","goma volcan","goma lac kivu"],
    kananga: ["kananga","kananga kasaï","kananga lulua"],
    mbuji_mayi: ["mbuji-mayi","mbuji mayi","mbuji-mayi kasaï","mbuji-mayi diamant"],
    tshikapa: ["tshikapa","tshikapa kasaï","tshikapa diamant"],
    kisangani: ["kisangani","kisangani tshopo","kisangani fleuve"],
    boma: ["boma","boma port","boma kongo-central"],
    muanda: ["muanda","muanda plage","muanda pétrole"]
  },

  traduction_en: {
    bread: "pain", meat: "viande", rice: "riz", flour: "farine", oil: "huile", sugar: "sucre", salt: "sel", milk: "lait", egg: "œuf", eggs: "œufs",
    fish: "poisson", chicken: "poulet", beef: "bœuf", pork: "porc", goat: "chèvre", lamb: "agneau", mutton: "mouton", vegetable: "légume", vegetables: "légumes", fruit: "fruit",
    fruits: "fruits", tomato: "tomate", onion: "oignon", potato: "pomme de terre", banana: "banane", plantain: "banane plantain", peanut: "arachide", groundnut: "arachide", spice: "épice", spices: "épices",
    drink: "boisson", water: "eau", juice: "jus", soda: "soda", beer: "bière", wine: "vin", coffee: "café", tea: "thé", biscuit: "biscuit", cookies: "biscuits",
    cake: "gâteau", chocolate: "chocolat", candy: "bonbon", sweets: "bonbons", ice: "glace", icecream: "glace", cheese: "fromage", butter: "beurre", yogurt: "yaourt", yoghurt: "yaourt",
    pasta: "pâtes", spaghetti: "spaghetti", noodles: "nouilles", honey: "miel", jam: "confiture", sauce: "sauce", pepper: "piment", lemon: "citron", house: "maison", home: "maison",
    apartment: "appartement", flat: "appartement", villa: "villa", plot: "parcelle", land: "terrain", lot: "lot", rent: "location", sale: "vente", bedroom: "chambre", room: "chambre",
    studio: "studio", kitchen: "cuisine", bathroom: "salle de bain", toilet: "toilette", living: "salon", garden: "jardin", garage: "garage", parking: "parking", car: "voiture", vehicle: "véhicule",
    motorcycle: "moto", motorbike: "moto", bike: "vélo", bicycle: "vélo", truck: "camion", bus: "bus", taxi: "taxi", tire: "pneu", engine: "moteur", battery: "batterie",
    phone: "téléphone", mobile: "portable", smartphone: "smartphone", computer: "ordinateur", laptop: "ordinateur portable", pc: "ordinateur", tablet: "tablette", tv: "télévision", television: "télévision", screen: "écran",
    monitor: "écran", headphone: "écouteurs", headphones: "écouteurs", speaker: "haut-parleur", charger: "chargeur", cable: "câble", printer: "imprimante", scanner: "scanner", keyboard: "clavier", mouse: "souris",
    camera: "caméra", watch: "montre", smartwatch: "montre connectée", router: "routeur", modem: "modem", job: "emploi", work: "travail", school: "école", university: "université", student: "étudiant",
    teacher: "enseignant", doctor: "médecin", hospital: "hôpital", clinic: "clinique", pharmacy: "pharmacie", medicine: "médicament", nurse: "infirmier", dentist: "dentiste", health: "santé", hospital: "hôpital",
    house: "maison", plot: "parcelle", location: "localisation", area: "zone", city: "ville", street: "rue", road: "route", village: "village", neighborhood: "quartier", district: "commune",
    what: "quoi", where: "où", when: "quand", how: "comment", why: "pourquoi", who: "qui", need: "besoin", want: "veux", looking: "cherche", search: "rechercher",
    buy: "acheter", sell: "vendre", rent: "louer", order: "commander", deliver: "livrer", find: "trouver", available: "disponible", price: "prix", cheap: "pas cher", expensive: "cher"
  },

  stopwords: [
    "je","tu","il","elle","on","nous","vous","ils","elles","me","te","se","moi","toi","lui","leur",
    "le","la","les","un","une","des","du","de","d'","l'","à","au","aux","et","ou","mais","donc","or","ni","car",
    "avec","sans","pour","par","dans","sur","sous","vers","chez","entre","depuis","pendant","avant","après",
    "ce","cet","cette","ces","mon","ton","son","ma","ta","sa","mes","tes","ses","notre","votre","leur","nos","vos","leurs",
    "ai","as","a","avons","avez","ont","avais","avait","avions","aviez","avaient","suis","es","est","sommes","êtes","sont",
    "veux","veut","voulons","voulez","veulent","voudrais","voudrait","cherche","cherches","cherchons","cherchez","cherchent",
    "besoin","aimerais","aimerait","peux","peut","pouvons","pouvez","peuvent","dois","doit","devons","devez","doivent",
    "svp","merci","please","si","il","faut","y","a","aussi","très","trop","peu","beaucoup","un","peu","pas","plus","moins",
    "bien","mal","tout","tous","toute","toutes","même","aussi","encore","déjà","jamais","toujours","souvent","parfois",
    "ici","là","là-bas","ailleurs","partout","nulle","part","maintenant","aujourd'hui","hier","demain","bientôt","tôt","tard",
    "bonjour","bonsoir","salut","coucou","hey","hello","hi","s'il","vous","plaît","stp","voir","regarde","regardez",
    "cherche","cherchons","trouve","trouvons","trouvez","voilà","voici","est-ce","que","qu'","quoi","qui","où","quand",
    "comment","pourquoi","combien","quel","quelle","quels","quelles","autre","autres","même","mêmes","tel","telle"
  ]
};
